# Análisis

In [3]:
#
import pandas as pd
pd.set_option('display.max_columns', None)

# 
import numpy as np

# 
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# 
import warnings
warnings.filterwarnings('ignore')

In [4]:
#lectura csv final
df_final = pd.read_csv('files/hr_final.csv', index_col = 0)
df_final.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
EmployeeNumber,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,41,True,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,Sales Executive,4,Single,5993.0,19479,8,True,True,11,3,1,80,0,8,0,1,6,4,0,5
2,49,False,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,3,Male,61,2,2,Research Scientist,2,Married,5130.0,24907,1,True,False,23,4,4,80,1,10,3,3,10,7,1,7
4,37,True,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,Male,92,2,1,Laboratory Technician,3,Single,2090.0,2396,6,True,True,15,3,2,80,0,7,3,3,0,0,0,0
5,33,False,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,4,Female,56,3,1,Research Scientist,3,Married,2909.0,23159,1,True,True,11,3,3,80,0,8,3,3,8,7,3,0
7,27,False,Travel_Rarely,591,Research & Development,2,1,Medical,1,1,Male,40,3,1,Laboratory Technician,2,Married,3468.0,16632,9,True,False,12,3,4,80,1,6,3,3,2,2,2,2

In [10]:
#Función para calcular el resumen estadístico de una variable:

def resumen_variable(df, columna):

    serie_original = df[columna]
    serie = serie_original.dropna()

    media = serie.mean()
    mediana = serie.median()
    moda = serie.mode()
    desviacion = serie.std()
    minimo = serie.min()
    maximo = serie.max()
    varianza = serie.var()
    q1 = serie.quantile(0.25)
    q3 = serie.quantile(0.75)
    rango_intercuartilico = q3 - q1
    rango = maximo - minimo

    if media != 0:
        coef_variacion = (desviacion / media) * 100
    else:
        coef_variacion = np.nan

    resumen = pd.DataFrame({
        "variable": [columna],
        "media": [round(media, 2)],
        "mediana": [round(mediana, 2)],
        "moda": [moda.iloc[0] if len(moda) > 0 else np.nan],
        "desviacion_estandar": [round(desviacion, 2)],
        "minimo": [round(minimo, 2)],
        "maximo": [round(maximo, 2)],
        "varianza": [round(varianza, 2)],
        "q1": [round(q1, 2)],
        "q3": [round(q3, 2)],
        "rango_intercuartilico": [round(rango_intercuartilico, 2)],
        "rango": [round(rango, 2)],
        "coeficiente_variacion": [round(coef_variacion, 2)]
    })

    return resumen

In [11]:
#Hacemos una función para automatizar que nos saque toda la información de cada variable numérica
def resumen_variables_numericas(df, columnas_numericas):

    tablas_resumen = []

    for columna in columnas_numericas:
        resumen = resumen_variable(df, columna)
        tablas_resumen.append(resumen)

    resumen_total = pd.concat(tablas_resumen, ignore_index=True)

    return resumen_total

In [ ]:
#Hacemos una lista de las variables numéricas
variables_numericas = df_final.select_dtypes(include=["int64", "float64"]).columns.tolist()

variables_numericas

In [13]:
resumen_total = resumen_variables_numericas(df_final, variables_numericas)
resumen_total

,variable,media,mediana,moda,desviacion_estandar,minimo,maximo,varianza,q1,q3,rango_intercuartilico,rango,coeficiente_variacion
0,Age,36.95,36.0,37.0,8.87,18.0,60.0,78.62,31.00,42.00,11.00,42.0,24.00
1,DailyRate,802.49,802.0,691.0,403.51,102.0,1499.0,162819.59,465.00,1157.00,692.00,1397.0,50.28
2,DistanceFromHome,9.19,7.0,2.0,8.11,1.0,29.0,65.72,2.00,14.00,12.00,28.0,88.19
3,Education,2.91,3.0,3.0,1.02,1.0,5.0,1.05,2.00,4.00,2.00,4.0,35.16
4,EmployeeCount,1.00,1.0,1.0,0.00,1.0,1.0,0.00,1.00,1.00,0.00,0.0,0.00
5,EnvironmentSatisfaction,2.72,3.0,3.0,1.09,1.0,4.0,1.19,2.00,4.00,2.00,3.0,40.16
6,HourlyRate,65.89,66.0,66.0,20.33,30.0,100.0,413.29,48.00,83.75,35.75,70.0,30.85
7,JobInvolvement,2.73,3.0,3.0,0.71,1.0,4.0,0.51,2.00,3.00,1.00,3.0,26.07
8,JobLevel,2.06,2.0,1.0,1.11,1.0,5.0,1.23,1.00,3.00,2.00,4.0,53.63
9,JobSatisfaction,2.74,3.0,3.0,1.09,1.0,4.0,1.20,2.00,4.00,2.00,3.0,39.99
10,MonthlyIncome,6483.52,4907.0,4907.0,4689.45,1009.0,19999.0,21990945.44,2926.75,8233.75,5307.00,18990.0,72.33
11,MonthlyRate,14313.10,14235.5,4223.0,7117.79,2094.0,26999.0,50662878.17,8047.00,20461.50,12414.50,24905.0,49.73
12,NumCompaniesWorked,2.69,2.0,1.0,2.50,0.0,9.0,6.24,1.00,4.00,3.00,9.0,92.75
13,PercentSalaryHike,15.21,14.0,11.0,3.66,11.0,25.0,13.40,12.00,18.00,6.00,14.0,24.06
14,PerformanceRating,3.15,3.0,3.0,0.36,3.0,4.0,0.13,3.00,3.00,0.00,1.0,11.44
15,RelationshipSatisfaction,2.71,3.0,3.0,1.08,1.0,4.0,1.17,2.00,4.00,2.00,3.0,39.86
16,StandardHours,80.00,80.0,80.0,0.00,80.0,80.0,0.00,80.00,80.00,0.00,0.0,0.00
17,StockOptionLevel,0.79,1.0,0.0,0.85,0.0,3.0,0.73,0.00,1.00,1.00,3.0,107.33
18,TotalWorkingYears,11.28,10.0,10.0,7.78,0.0,40.0,60.54,6.00,15.00,9.00,40.0,68.98
19,TrainingTimesLastYear,2.81,3.0,3.0,1.26,0.0,6.0,1.59,2.00,3.00,1.00,6.0,44.82
20,WorkLifeBalance,2.76,3.0,3.0,0.71,1.0,4.0,0.50,2.00,3.00,1.00,3.0,25.59
21,YearsAtCompany,7.01,5.0,5.0,6.13,0.0,40.0,37.53,3.00,9.00,6.00,40.0,87.42
22,YearsInCurrentRole,4.23,3.0,2.0,3.62,0.0,18.0,13.13,2.00,7.00,5.00,18.0,85.67
23,YearsSinceLastPromotion,2.19,1.0,0.0,3.22,0.0,15.0,10.38,0.00,3.00,3.00,15.0,147.29
24,YearsWithCurrManager,3.96,3.0,2.0,3.35,0.0,17.0,11.24,2.00,7.00,5.00,17.0,84.62